version: '2'

networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  app:
    build:
      context: ../../
      dockerfile: docker/release/Dockerfile
      args:
        app_version: ${APP_VERSION}
    environment:
      HTTP_HOST: app
      HTTP_PORT: ${HTTP_PORT}
      MARKET_DATA_ADDRESS: market
      CLUSTER_GROUP_NAME: quote-generator
      CLUSTER_GROUP_PASSWORD: password
  test:
    image: dockerproductionaws/microtrader-test
    links:
      - app
    environment:
      HTTP_HOST: app
      HTTP_PORT: ${HTTP_PORT}
      MARKET_DATA_ADDRESS: market
      CLUSTER_GROUP_NAME: quote-generator
      CLUSTER_GROUP_PASSWORD: password
    dns_search: .
    command:
      - mvn
      - test
      - -Dtest=QuoteGeneratorTest
      - -Dvertx.hazelcast.config=/app/conf/cluster.xml
  agent:
    image: dockerproductionaws/ansible
    links:
      - app
    environment:
      PROBE_HOST: app
      PROBE_PORT: ${HTTP_PORT}
