version: '2'

networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  app:
    build:
      context: ../../
      dockerfile: docker/release/Dockerfile
      args:
        app_version: ${APP_VERSION}
    environment:
      HTTP_PORT: ${HTTP_PORT}
    networks:
      default:
        aliases:
          - quote-generator
    command:
      - java
      - -jar
      - /app/quote-generator-${APP_VERSION}-fat.jar
      - -conf=/app/conf/config.json
      - -Dvertx.hazelcast.config=/app/conf/cluster.xml
      - -cluster